FROM tensorflow/tensorflow:latest
LABEL maintainer "hj <shgpwls374@gmail.com>"

COPY ./lib/ /module

ENV MODELPATH='/model'
ENV LIBPATH='/module'
ENV DATAPATH='/data'

WORKDIR /app
COPY train/train_new.py .

RUN pip3 install numpy pandas keras pillow flask

ENTRYPOINT ["python"]
CMD ["train_new.py"]