FROM tensorflow/tensorflow:latest
LABEL maintainer "hj <shgpwls374@gmail.com>"

COPY ./lib/ /module

ENV MODELPATH='/model'
ENV LIBPATH='/module'

WORKDIR /app
COPY infer/infer_new.py .

RUN pip3 install numpy pandas keras pillow flask

ENTRYPOINT ["python"]
CMD ["infer_new.py"]