FROM tensorflow/tensorflow:latest

COPY ./lib/ /module

ENV MODELPATH='./model'
ENV LIBPATH='./module'

WORKDIR /app
COPY infer/infer.py .

RUN pip3 install numpy pandas keras pillow flask

ENTRYPOINT ["python"]
CMD ["infer.py"]