FROM tensorflow/tensorflow:latest

COPY ./lib/ /module

ENV MODELPATH='./model'
ENV LIBPATH='./module'
ENV DATAPATH='./data'

WORKDIR /app
COPY train/train.py .

RUN pip3 install numpy keras pillow flask

ENTRYPOINT ["python"]
CMD ["train.py"]